### ISSUE TITLE
Netsim: Specifying NETSIM_GRPC_PORT disables web interface

### ISSUE THREAD

**Issue by akuker** [google/rootcanal#26]
For my use case, I need to specify a GRPC port, using the NETSIM_GRPC_PORT environment variable. However, when the GRPC port is specified, the web server is disabled. These two features should not be tied together.

In `rust/daemon/src/service.rs`, there is a comment that the web server is disable due to a "google3 forge job". This seems like an arbitrary way of disabling the web server that limits the flexibility of netsimd.

```
    /// Runs netsim web server
    fn run_web_server(&self) -> Option<u16> {
        // Environment variable "NETSIM_GRPC_PORT" is set in google3 forge jobs.
        // If set, don't start http server.
        let forge_job = env::var("NETSIM_GRPC_PORT").is_ok();
        match !forge_job && !self.service_params.no_web_ui {
            true => Some(run_http_server(self.service_params.instance_num)),
            false => None,
        }
    }
```

Could netsimd please be updated to allow the webserver to still be used when the GRPC port is specified? Perhaps a separate environment variable to disable the web server?

**Comment by hchataing** [comment]
I forwarded the issue internally, thanks for the report :+1:

**Comment by hchataing** [comment]
The netsim team has added `NETSIM_NO_WEB_SERVER` to independently enable or disable the web server.
Let me know if this option sounds good to you.

**Comment by akuker** [comment]
That sounds great! Thank you @hchataing

**Comment by hyunjaemoon-work** [comment]
Hello @akuker!

We've landed a change for [Netsim](https://cs.android.com/android/platform/superproject/main/+/main:tools/netsim/rust/daemon/src/service.rs;l=118). You should be able to freely specify `NETSIM_GRPC_PORT` without disabling the web interface.

However if you wish to use either Cloud Emulators or Android Emulators, there may be some delay due to release propagation for external use (2 weeks to 1 month). The immediate way to experiment with the new env variable would be through [downloading and building the source directly](https://source.android.com/docs/setup/download/downloading)

Thank you for spotting this issue!

**Comment by akuker** [comment]
Thank you @hyunjaemoon-work !!
